{{- if .Values.rbac.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    songlaa.ch/purpose: webshell
    {{- include "webshell.labels" . | nindent 4 }}
  name: songlaa-webshell-{{ .Values.user }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
{{- end -}}
